# Generated by Django 5.1.1 on 2024-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBagInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_zone', models.CharField(choices=[('North', 'North'), ('South', 'South')], max_length=5)),
                ('a_positive', models.PositiveIntegerField(default=0)),
                ('a_negative', models.PositiveIntegerField(default=0)),
                ('b_positive', models.PositiveIntegerField(default=0)),
                ('b_negative', models.PositiveIntegerField(default=0)),
                ('o_positive', models.PositiveIntegerField(default=0)),
                ('o_negative', models.PositiveIntegerField(default=0)),
                ('ab_positive', models.PositiveIntegerField(default=0)),
                ('ab_negative', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
