# Generated by Django 5.1.1 on 2024-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_bloodbaginfo_bloodbankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='working_zone',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
