# Generated by Django 5.1.1 on 2024-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0004_bloodbaginfo_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbaginfo',
            name='branch',
            field=models.CharField(default='North', max_length=20),
        ),
    ]
