# Generated by Django 5.1.1 on 2024-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0006_remove_bloodbaginfo_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='working_zone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
