# Generated by Django 5.1.15 on 2026-09-20 00:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0008_userprofile_is_donor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodbaginfo',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'blood bag record', 'verbose_name_plural': 'blood bag records'},
        ),
        migrations.AlterModelOptions(
            name='bloodbankinfo',
            options={'ordering': ['branch_zone'], 'verbose_name': 'blood bank branch', 'verbose_name_plural': 'blood bank branches'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='bloodbaginfo',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_bag_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodbaginfo',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodbaginfo',
            name='branch',
            field=models.CharField(choices=[('North', 'Dhaka North'), ('South', 'Dhaka South')], default='North', max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodbaginfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloodbaginfo',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Positive when blood is collected, negative when it is issued.'),
        ),
        migrations.AlterField(
            model_name='bloodbankinfo',
            name='branch_zone',
            field=models.CharField(choices=[('North', 'Dhaka North'), ('South', 'Dhaka South')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodbankinfo',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number (digits, spaces and dashes only).', regex='^\\+?[0-9][0-9\\s\\-]{5,19}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Donors must be between 18 and 65 years old.', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_donor',
            field=models.BooleanField(default=False, help_text='Opted in to be contacted as a volunteer donor.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number (digits, spaces and dashes only).', regex='^\\+?[0-9][0-9\\s\\-]{5,19}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_zone',
            field=models.CharField(blank=True, choices=[('North', 'Dhaka North'), ('South', 'Dhaka South')], help_text='Branch managed by this user. Managers only.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(choices=[('North', 'Dhaka North'), ('South', 'Dhaka South')], max_length=5),
        ),
        migrations.AddIndex(
            model_name='bloodbaginfo',
            index=models.Index(fields=['branch', 'blood_group'], name='bloodbank_b_branch_b5f483_idx'),
        ),
    ]
